# Site Settings
title: GoodzSex - Os Melhores Videos Pornôs Grátis
email: goodzsexporn@gmail.com
description: Some text about your blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.goodzsex.com" # the base hostname & protocol for your site
google_analytics: "UA-124267055-1"

include: ["_pornstar"]

paginate: 24
paginate_path: "/pagina/:num/"

blog:
    tags:
        url: /tags/
        title_prefix: "blog - tag: "
        layout: tag.html

# User Settings
username: GoodzSex
user_description: Some text about you.
disqus_username: goodzsex

# Social Media
# Remove the item if you don't need it
github_username: github_username
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Inicio
    url: /
  - title: Sobre
    url: /sobre/
  - title: Cadastro
    url: /cadastro/
  - title: Contato
    url: /contato/
  - title: DMCA
    url: /dmca/
  - title: Video Deletado?
    url: /deletado/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
